### ISSUE TITLE
Unhandled stream error in pipe

### ISSUE THREAD

**Issue by OopsJunQi** [alonperl/X-Ray-DNS#2]
Hello:
After I clicked "show reslut"button on dns.html ，the Webserver got the following errors:

internal/streams/legacy.js:57
      throw er; // Unhandled stream error in pipe.

Error: ETIMEDOUT
    at Timeout._onTimeout (/etc/webserver/node_modules/request/request.js:849:19)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)

How can I solve this problem? thanks in advance.

**Comment by OopsJunQi** [comment]
Solved this after I changed the domain name in "http://pprod.sit.fraunhofer.de:3000".

**Comment by OopsJunQi** [comment]
> Solved this after I changed the domain name in "http://pprod.sit.fraunhofer.de:3000".

Uh.. 
But how could I get those files in the path'./../../rawdns' on the 'Parent/Attacker/Victim' file server?
Where do those files came from?

https://github.com/alonperl/X-Ray-DNS/blob/495252536878306a8bc42bd9ad8a72a6c14ed8a3/Parent_Attacker_Victim/File%20Server/app.js#L3
